scripts/reapply: Reset head on reapply failures

diff --git a/scripts/reapply b/scripts/reapply
--- a/scripts/reapply
+++ b/scripts/reapply
@@ -1,21 +1,32 @@
 #!/usr/bin/env bash
 
-set -e
+set -eE
+trap 'error' ERR
 
 if [[ $# -eq 0 ]]; then
 	echo "Usage: $0 <commits>..." >&2
 	exit 1
 fi
 
+error() {
+	local errExitCode=$?
+	if [[ "$errResetTo" != "" ]]; then
+		echo "Failed to reapply, resetting to $errResetTo" >&2
+		git reset --hard "$errResetTo"
+	fi
+	exit $errExitCode
+}
+
 while [ $# -ne 0 ]; do
 	case $1 in
 	*)
+		errResetTo="$(git rev-parse HEAD)"
 		git revert --no-edit "$1"
 		./scripts/pick --one "$(git log -1 "$1" --format='%(trailers:key=Change-Id,valueonly,separator=)')"
 		newcommit="$(git rev-parse HEAD)"
 		git reset --soft HEAD^^
 		if ! git diff-index --quiet HEAD --; then
-			git commit -m "Reapply: $(git log -1 --format=%B "$newcommit")$(echo)Reapply: $1"
+			git commit -m "$(printf 'Reapply: %s\nReapply: %s' "$(git log -1 --format=%B "$newcommit")" "$1")"
 		fi
 		;;
 	esac
