bash-tpl: update to v0.8.0

diff --git a/external/bash-tpl b/external/bash-tpl
--- a/external/bash-tpl
+++ b/external/bash-tpl
@@ -7,7 +7,7 @@
 # See the accompanying LICENSE file, if present, or visit:
 #   https://opensource.org/licenses/MIT
 #######################################################################
-VERSION="v0.7.1"
+VERSION="v0.8.0"
 #######################################################################
 # Bash-TPL: A Smart, Lightweight shell script templating engine
 #
@@ -272,7 +272,7 @@ function reset_template_regexes() {
 
 	d="${DIRECTIVE_DELIM}"
 	escape_regex d
-	DIRECTIVE_REGEX="^([[:blank:]]*)${d}([a-zA-Z_-]+)(.*)\$"
+	DIRECTIVE_REGEX="^([[:blank:]]*)${d}([a-zA-Z_-]+\??)(.*)\$"
 
 	d="${COMMENT_DELIM}"
 	escape_regex d
@@ -342,6 +342,26 @@ function reset_template_regexes() {
 #
 function trim() {
 	read -r "$1" <<< "${!1}"$'\n'
+}
+##
+# escape_string
+# Escapes value compatible with posix `printf %b`
+# usage: escape_string varname
+#
+function escape_string {
+	# Escape '\' first since we'll be adding more later
+	local e="${!1//$'\\'/\\}"
+	# Some man pages mention \0NNN but in practice it seems \NNN is also works.
+	e="${e//\\/\\\\}"
+	e="${e//\'/\\0047}"
+	e="${e//$'\a'/\\a}"
+	e="${e//$'\b'/\\b}"
+	e="${e//$'\f'/\\f}"
+	e="${e//$'\n'/\\n}"
+	e="${e//$'\r'/\\r}"
+	e="${e//$'\t'/\\t}"
+	e="${e//$'\v'/\\v}"
+	printf -v "${1}" "'%s'" "${e}"
 }
 
 ##
@@ -517,26 +537,32 @@ function print_text() {
 # $2 = full line of text to process
 #
 function process_tags() {
-	local stmt_indent line args arg quoted
+	local stmt_indent line formats args arg quoted
 	stmt_indent="${1}"
 	line="${2}"
-	args=""
+	formats=""
+	args=()
 	while [ -n "${line}" ]; do
 		# echo "# LINE @ START: $(declare -p line)" >&2
 		if [[ "${line}" =~ $TAG_TEXT_REGEX ]]; then
 			# echo "# TEXT TAG MATCH: $(declare -p BASH_REMATCH)" >&2
-			printf -v quoted "%q" "${BASH_REMATCH[1]}"
-			args="${args}${quoted}"
+			quoted="${BASH_REMATCH[1]}"
+			escape_string quoted
+			#printf -v quoted "%q" "${BASH_REMATCH[1]}"
+			formats="${formats}%b"
+			args+=("${quoted}")
 			line="${BASH_REMATCH[2]}"
 		elif [[ "${line}" =~ $TAG_QUOTE_REGEX ]]; then
 			# echo "# QUOTE TAG MATCH: $(declare -p BASH_REMATCH)" >&2
-			args="${args}\"${BASH_REMATCH[1]}\""
+			formats="${formats}%s"
+			args+=("\"${BASH_REMATCH[1]}\"")
 			line="${BASH_REMATCH[6]}"
 		elif [[ "${line}" =~ $TAG_STATEMENT_REGEX ]]; then
 			# echo "# STMT TAG MATCH: $(declare -p BASH_REMATCH)" >&2
 			arg="${BASH_REMATCH[1]}"
 			trim arg
-			args="${args}\"\$(${arg})\""
+			formats="${formats}%s"
+			args+=("\"\$(${arg})\"")
 			line="${BASH_REMATCH[5]}"
 		# Check standard regex last as it's a super-set of quote and stmt regex
 		#
@@ -544,21 +570,25 @@ function process_tags() {
 			# echo "# STD TAG MATCH: $(declare -p BASH_REMATCH)" >&2
 			arg="${BASH_REMATCH[1]}"
 			trim arg
-			args="${args}\"${arg}\""
+			formats="${formats}%s"
+			args+=("\"${arg}\"")
 			line="${BASH_REMATCH[5]}"
 		# Assume next character is TEXT - extract and process remainder
 		#
 		elif [[ "${line}" =~ (.)(.*) ]]; then
-			# echo "# DEFAULT: Assuming first char is TEXT: $(declare -p line)"
-			printf -v quoted "%q" "${BASH_REMATCH[1]}"
-			args="${args}${quoted}"
+			# echo "# DEFAULT: Assuming first char is TEXT: $(declare -p line)" >&2
+			quoted="${BASH_REMATCH[1]}"
+			escape_string quoted
+			#printf -v quoted "%q" "${BASH_REMATCH[1]}"
+			formats="${formats}%b"
+			args+=("${quoted}")
 			line="${BASH_REMATCH[2]}"
 		fi
 		# echo "# LINE @ END: $(declare -p line)" >&2
 	done
 	local stmt
-	if [ -n "${args}" ]; then
-		printf -v stmt "printf \"%%s\\\\n\" %s" "${args}"
+	if [[ ${#args[@]} -gt 0 ]]; then
+		printf -v stmt "printf \"%s\\\\n\" %s" "${formats}" "${args[*]}"
 	else
 		printf -v stmt "printf \"\\\\n\""
 	fi
@@ -587,7 +617,11 @@ function process_directive() {
 	directive="${2}"
 	normalize_directive directive
 	case "${directive}" in
-		INCLUDE)
+		INCLUDE | INCLUDE\?)
+			local file_not_found_ok=""
+			if [ "${directive}" = "INCLUDE?" ]; then
+				file_not_found_ok="1"
+			fi
 			local indent="${1}"
 			if [[ "${indent}" == "${BLOCK_INDENT}"* ]]; then
 				indent="${indent/#$BLOCK_INDENT/}"
@@ -608,6 +642,7 @@ function process_directive() {
 				--txt-delim "${TEXT_DELIM}" \
 				--dir-delim "${DIRECTIVE_DELIM}" \
 				--cmt-delim "${COMMENT_DELIM}" \
+				${file_not_found_ok:+'--file-not-found-ok'} \
 				"${args_arr[@]}"
 			;;
 		DELIMS)
@@ -1216,6 +1251,10 @@ function parse_args() {
 				BASE_BLOCK_INDENT="${2}"
 				shift 2
 				;;
+			--file-not-found-ok) # internal flag to support .INCLUDE?
+				FILE_NOT_FOUND_OK=1
+				shift
+				;;
 			-)
 				__ARGS+=("$1")
 				shift
@@ -1250,6 +1289,11 @@ function main() {
 	reset_delims
 	parse_env_delims
 
+	FILE_NOT_FOUND_OK=""
+	if [ -n "${BASH_TPL_FILE_NOT_FOUND_OK}" ]; then
+		FILE_NOT_FOUND_OK="1"
+	fi
+
 	parse_args "$@"
 	set -- "${__ARGS[@]}"
 	unset __ARGS
@@ -1272,8 +1316,13 @@ function main() {
 			# File argument points to non-existing/readable file
 			#
 			if [[ ! -r "${1}" ]]; then
-				echo "File not found: '${1}'" >&2
-				exit 1
+				if [ -z "${FILE_NOT_FOUND_OK}" ]; then
+					echo "File not found: '${1}'" >&2
+					exit 1
+				else
+					# Fail silently, no message, no error code
+					exit 0
+				fi
 			fi
 			# File argument is good, re-route it to stdin
 			#
